
# All-blog Settings
host:   http://localhost:3000
posts:  /posts
count:  50
title:  MicrowaveJS Blog
desc:   An example MicrowaveJS blog that you'll want to read again and again!
author: Blog Author

# DISQUS Settings
comments:    true
disqusname:  testblog

# Display Settings
next:  Newer Posts
prev:  Older Posts