
# All-blog Settings
host:   http://localhost:3000
posts:  /posts
title:  MicrowaveJS Blog
count:  50

# DISQUS Settings
comments:    true
disqusname:  testblog

# Display Settings
next:  Newer Posts
prev:  Older Posts